Fix build on FreeBSD.
fstream expects char*

plaintextextractor.cpp:102:19: error: no matching constructor for
initialization of 'std::ifstream' (aka 'basic_ifstream<char>')
    std::ifstream fstream(QFile::encodeName(result->inputUrl()));

REVIEW: 124733